name: unittest

on: [push, pull_request]

jobs:
  unittest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Use Node.js
      uses: actions/setup-node@v4
    - run: npm install
    - run: npm run downport
    - run: npm run unit
